name: 'Task Manager App'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    env:
      SECRET_TOKEN: 239482
      MONGO_URL: mongodb://localhost:27017/TaskManagerDev
      PORT: 3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.15.0

      - name: Install pnpm
        run: npm install pnpm@7 -g
        shell: bash

      - name: 'Install dependencies'
        run: pnpm install
        shell: bash

      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 5.0

      - name: 'Wait for MongoDB to initialize'
        run: |
          for i in {1..30}; do
            nc -z localhost 27017 && echo "MongoDB is up" && break
            echo "Waiting for MongoDB to initialize..."
            sleep 5
          done
        shell: bash



      - name: 'Run application'
        run: pnpm run start:dev
        shell: bash
