name: 'Task Manager App'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_DATABASE: TaskManagerDev

        ports:
          - 27017:27017

    env:
      SECRET_TOKEN: 239482
      MONGO_URL: mongodb:/0.0.0.0:27017/TaskManagerDev
      PORT: 3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.15.0

      - name: Install pnpm
        run: npm install pnpm@7 -g
        shell: bash

      - name: 'Install dependencies'
        run: pnpm install
        shell: bash

      - name: 'Run tests'
        run: pnpm test
        shell: bash

      - name: 'Run e2e tests'
        run: pnpm test:e2e
        shell: bash

      - name: 'Run application'
        run: pnpm run start:dev
        shell: bash
